[package]
name = "soroban-synth-wasm"
description = "Utilities for synthesizing soroban contract wasm modules."
homepage = "https://github.com/stellar/rs-soroban-env"
repository = "https://github.com/stellar/rs-soroban-env"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
version = "26.0.0"
edition = "2021"
rust-version = "1.84.0"
publish = false

[dependencies]
wasm-encoder = "=0.38.1"
wasmparser = "=0.116.1"
soroban-env-common = { version = "=26.0.0", path = "../soroban-env-common", default-features = false }
stellar-xdr = { version = "=26.0.0", default-features = false, features = ["curr", "std"] }
arbitrary = { version = "1.3.2", features = ["derive"] }
soroban-env-macros = { version = "=26.0.0", path = "../soroban-env-macros" }

[features]
testutils = ["soroban-env-common/testutils"]
adversarial = []

[dev-dependencies]
expect-test = "1.4.1"
wasmprinter = "0.2.72"
